CREATE DATABASE MVN_BOOK;

CREATE TABLE ACCOUNT(
	ID VARCHAR(64) NOT NULL PRIMARY KEY , 
	NAME VARCHAR(64) NOT NULL , 
	EMAIL VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	ACTIVATED BOOLEAN
);